name: nupano
services:

  runtime:
    user: root #required for windows to access docker.sock
    restart: always
    image: public.ecr.aws/nupano/nupano-runtime:latest
    environment:
      - logging.level.com.nupano=INFO #INFO or DEBUG
      - nupano.description.manufacturer=not specified
      - nupano.description.model-name=Generic PC
      - nupano.description.serial-number= #default: UUID of Runtime
      #- nupano.machine.pairing.proxy.host=
      #- nupano.machine.pairing.proxy.port=
      #- nupano.machine.pairing.proxy.username=
      #- nupano.machine.pairing.proxy.password=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # access to docker socket
      - nupano_data:/nupano                         # persist nupano runtime data
    networks:
      - nupano_network
    ports:
      - 61100:61100/tcp

  discovery:
    restart: always
    image: public.ecr.aws/nupano/nupano-runtime-discovery:latest
    network_mode: host #-> SSDP
    environment:
      - logging.level.com.nupano=INFO #INFO or DEBUG


networks:
  nupano_network:
    name: nupano
    driver: bridge

volumes:
  nupano_data:
