name: nupano
services:
  runtime:
    user: root #required for windows to access docker.sock
    restart: always
    image: ghcr.io/nupano/nupano-runtime:3.1.2
    environment:
      - logging.level.com.nupano=INFO
      - nupano.description.manufacturer=not specified
      - nupano.description.model-name=Generic PC
      - nupano.description.serial-number= #default: Runtime id
      #- nupano.proxy.host=
      #- nupano.proxy.port=
      #- nupano.proxy.username=
      #- nupano.proxy.password=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # access to docker socket
      - nupano_data:/nupano # persist nupano runtime data
    networks:
      - nupano_network
    ports:
      - 61100:61100/tcp

networks:
  nupano_network:
    name: nupano
    driver: bridge

volumes:
  nupano_data:
